--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: mywebrs
spec: 
  replicas: 3
  selector:
   matchExpressions:
    - { key: env, operator: In, values: [ production ] }
    - { key: region, operator: In, values: [ IN ] }
  template: 
    metadata: 
      labels: 
        dc: "2"
        env: production
        region: IN
      name: myweb-pod
    spec: 
      containers: 
        - 
          image: httpd
          name: myweb-con
